# Generated by Django 3.2.20 on 2024-04-08 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(choices=[('LV1', '1А'), ('LV2', '1Б'), ('LV3', '2А'), ('LV4', '2Б'), ('LV5', '3А'), ('LV6', '3Б')], default='LV1', max_length=3, verbose_name='Зима')),
                ('spring', models.CharField(choices=[('LV1', '1А'), ('LV2', '1Б'), ('LV3', '2А'), ('LV4', '2Б'), ('LV5', '3А'), ('LV6', '3Б')], default='LV1', max_length=3, verbose_name='Весна')),
                ('summer', models.CharField(choices=[('LV1', '1А'), ('LV2', '1Б'), ('LV3', '2А'), ('LV4', '2Б'), ('LV5', '3А'), ('LV6', '3Б')], default='LV1', max_length=3, verbose_name='Лето')),
                ('autumn', models.CharField(choices=[('LV1', '1А'), ('LV2', '1Б'), ('LV3', '2А'), ('LV4', '2Б'), ('LV5', '3А'), ('LV6', '3Б')], default='LV1', max_length=3, verbose_name='Осень')),
            ],
        ),
        migrations.CreateModel(
            name='Tourists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('otc', models.CharField(max_length=100, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Почта')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
        ),
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pereval',
            name='autumn_lev',
        ),
        migrations.RemoveField(
            model_name='pereval',
            name='spring_lev',
        ),
        migrations.RemoveField(
            model_name='pereval',
            name='summer_lev',
        ),
        migrations.RemoveField(
            model_name='pereval',
            name='winter_lev',
        ),
        migrations.AddField(
            model_name='images',
            name='images',
            field=models.ImageField(default='default_image.jpg', upload_to='static/images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='coords',
            name='height',
            field=models.IntegerField(verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='coords',
            name='latitude',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='coords',
            name='longitude',
            field=models.FloatField(verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='images',
            name='pereval_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='camp.pereval', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='beauty_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='connect',
            field=models.CharField(default='', max_length=100, verbose_name='Что соединяет'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='coord_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pereval_coord', to='camp.coords', verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='other_titles',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='status',
            field=models.CharField(choices=[('NW', 'Новый'), ('PN', 'В работе'), ('AC', 'Принято'), ('RJ', 'Не принято')], default='Новый', max_length=10, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='pereval',
            name='level_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pereval_level', to='camp.level', verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='tourist_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pereval_user', to='camp.tourists', verbose_name='Пользователь'),
        ),
        migrations.DeleteModel(
            name='Tourist',
        ),
    ]
