# Generated by Django 3.2.25 on 2024-04-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0002_auto_20240408_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourists',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Почта'),
        ),
    ]
